services:
  fronend-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: simple_next_app_dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env
      - ./.env.local
      - ./.env.development
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
      - app_next:/app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev

  fronend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: simple_next_app_prod
    ports:
      - "3001:3000"
    env_file:
      - ./.env
      - ./.env.local
      - ./.env.production
    volumes:
      - app_node_modules:/app/node_modules
    environment:
      - NODE_ENV=production
    command: "npm run start"

volumes:
  app_node_modules:
    driver: local
  app_next:
    driver: local
